# Generated by Django 4.2.3 on 2023-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='desc',
            field=models.TextField(default='no des available'),
        ),
    ]
